#!/bin/sh
# OpenClaw Startup Script (v147 - Active Health Check & Failover)
# Solves 'hanging' issues by actively probing port 3000.

mkdir -p /root/.openclaw

echo "[STARTUP] Generating config v145 (Model: gemini-1.5-flash-latest)..."
node /root/clawd/configure.js

echo "[STARTUP] Starting OpenClaw..."
rm -f /root/openclaw.log

# Start OpenClaw with log piping
openclaw 2>&1 | tee /root/openclaw.log &
OPENCLAW_PID=$!

echo "[STARTUP] OpenClaw started (PID: $OPENCLAW_PID). Waiting for port 3000..."

# Prepare Failover Server Script
cat <<EOF > /root/failover_server.js
const http = require('http');
const fs = require('fs');
const port = 3000;
const logPath = '/root/openclaw.log';

http.createServer((req, res) => {
    let logContent = 'No log found.';
    try {
        if (fs.existsSync(logPath)) {
            logContent = fs.readFileSync(logPath, 'utf8');
        }
    } catch (e) { logContent = 'Error reading log: ' + e.message; }

    const html = \`
    <html>
    <head><title>OpenClaw Startup Failed</title></head>
    <body style="background:#1a1a1a; color:#ff5555; font-family:monospace; padding:20px;">
        <h1>OpenClaw Startup Failed (v147)</h1>
        <p>The application failed to bind port 3000 within the timeout period. Here are the logs:</p>
        <pre style="background:#000; padding:15px; overflow:auto; border:1px solid #555;">\${logContent}</pre>
        <hr>
        <p><em>Generated by Moltbot Active Health Check</em></p>
    </body>
    </html>\`;

    res.writeHead(503, { 'Content-Type': 'text/html' });
    res.end(html);
}).listen(port, () => {
    console.log('[FAILOVER] Log server running on port ' + port);
});
EOF

# Active Health Check Loop
# Wait up to 30 seconds for specific port response
MAX_RETRIES=30
count=0

while [ $count -lt $MAX_RETRIES ]; do
  # Check if PID is still alive first
  if ! kill -0 $OPENCLAW_PID 2>/dev/null; then
     echo "[CRITICAL] OpenClaw process DIED unexpectedly."
     break # Break loop to start failover
  fi

  # Check if port 3000 is listening and responding
  if curl -s -m 1 http://127.0.0.1:3000 > /dev/null; then
    echo "[HEALTH] OpenClaw is UP and responding on port 3000!"
    # Process is healthy. We now wait for it to exit (keep container alive)
    wait $OPENCLAW_PID
    exit 0
  fi

  sleep 1
  count=$((count+1))
  # Echo to stdout for Cloudflare logs
  echo "[STARTUP] Waiting for port 3000... ($count/$MAX_RETRIES)"
done

echo "[CRITICAL] OpenClaw Startup TIMED OUT or DIED."
echo "[CRITICAL] Killing process $OPENCLAW_PID (if alive) and starting failover..."

# Force kill if still arguably alive
kill -9 $OPENCLAW_PID 2>/dev/null

# Start Failover Server
exec node /root/failover_server.js
