#!/bin/sh
# OpenClaw Startup Script (v145 - Correct Model Name & Production Boot)
# Reverts dummy server usage and attempts to start OpenClaw with correct config.

mkdir -p /root/.openclaw

echo "[STARTUP] Generating config v145 (Model: gemini-1.5-flash-latest)..."
node /root/clawd/configure.js

echo "[STARTUP] Starting OpenClaw..."
# Standard cleanup
rm -f /root/openclaw.log

# Start OpenClaw with log piping to both file (for emergency-log) and stdout (for Cloudflare logs)
# Using 2>&1 to capture stderr as well.
# We trust that the model name fix will prevent the immediate crash.
openclaw 2>&1 | tee /root/openclaw.log &
OPENCLAW_PID=$!

echo "[STARTUP] OpenClaw started (PID: $OPENCLAW_PID). Logs are streaming."

# Monitor the process. If it dies, the container will exit (and restart),
# effectively signaling a crash to Cloudflare.
# However, to allow 'emergency-log' to work, we might want to keep it alive slightly longer?
# No, user wants real fix. If it crashes, let it crash (or 500).
# But for debugging 500s, we DO need it to stay alive if it crashes immediately.

# Survival loop & Failover Strategy
# If OpenClaw dies, we MUST start a backup server on port 3000 
# so the user sees the error instead of a connection timeout/hang.

while true; do
  if kill -0 $OPENCLAW_PID 2>/dev/null; then
    sleep 5
  else
    echo "[CRITICAL] OpenClaw process EXITED at $(date)."
    echo "Starting Failover Log Server on port 3000..."
    
    # Create a failover server that serves the log
    cat <<EOF > /root/failover_server.js
const http = require('http');
const fs = require('fs');
const port = 3000;
const logPath = '/root/openclaw.log';

http.createServer((req, res) => {
    let logContent = 'No log found.';
    try {
        if (fs.existsSync(logPath)) {
            logContent = fs.readFileSync(logPath, 'utf8');
        }
    } catch (e) { logContent = 'Error reading log: ' + e.message; }

    const html = \`
    <html>
    <head><title>OpenClaw Crashed</title></head>
    <body style="background:#1a1a1a; color:#ff5555; font-family:monospace; padding:20px;">
        <h1>OpenClaw Crash Report (v146)</h1>
        <p>The application process exited unexpectedly. Here are the logs:</p>
        <pre style="background:#000; padding:15px; overflow:auto; border:1px solid #555;">\${logContent}</pre>
        <hr>
        <p><em>Generated by Moltbot Failover System</em></p>
    </body>
    </html>\`;

    res.writeHead(500, { 'Content-Type': 'text/html' });
    res.end(html);
}).listen(port, () => {
    console.log('[FAILOVER] Log server running on port ' + port);
});
EOF
    
    # Run the failover server forever
    exec node /root/failover_server.js
  fi
done
